#General configuration
[general]
#Time Interval in seconds for when the server polls the whitelist changes from the database. (Warning! Time lower than 5 sec may affect performace.)
#Range: > 1
syncTimer = 60
#Option on whether to sync the server's op list to the database.
syncOpList = false
#Mode for the database. To use the WEB service, go to https://whitelistsync.com/ for instructions.
#Allowed Values: MYSQL, SQLITE, WEB
databaseMode = "MYSQL"
#Enable verbose logging.
verboseLogging = false
#MySQL configuration (To enable mySQL, refer to the mode setting in the general configuration).
[mySQL]
#IP for your mySQL server.
mysqlIp = "${CFG_DB_HOST}"
#Username for your mySQL server.
mysqlUsername = "${CFG_DB_USER}"
#Name for your mySQL database (No spaces!).
mysqlDbName = "${CFG_DB_NAME}"
#Password for your mySQL server.
mysqlPassword = "${CFG_DB_PASS}"
#Port for your mySQL server.
#Range: 1 ~ 65535
mysqlPort = ${CFG_DB_PORT}
#Sqlite configuration (To enable Sqlite, refer to the mode setting in the general configuration).
[sqlite]
#Insert System Path for your SQLite database file. This should be the same for all your servers you want to sync!
sqliteDatabasePath = "./whitelistSync.db"
#Web configuration (To enable Web, refer to the mode setting in the general configuration).
[web]
#Option to enable banned IPs sync.
webSyncBannedIps = false
#API Key for the web service. You can generate one by logging into the web service and adding a new API key to your account.
webApiKey = ""
#Host for the web service. This should be the URL of the web service. You should never need to change this.
webApiHost = "https://whitelistsync.com/"
#Option to enable banned players sync.
webSyncBannedPlayers = false