version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
naturalist = true
createfood = true
supplementaries = true
farmersdelight = true
create_new_age = true
fishofthieves = true
createbigcannons = true
alloy_forgery = true
megacells = true
chipped = true
betternether = true
create = true
betterend = true
oceansdelight = true
brewinandchewin = true
interiors = true
estrogen = true
mcwbiomesoplenty = true
another_furniture = true
gtceu = true
biomeswevegone = true
createoreexcavation = true
copycats = true
minecraft = true
createaddition = true
sliceanddice = true
molten_metals = true
createdieselgenerators = true
bosses_of_mass_destruction = true
createdeco = true
lolmcvbop = true
betterarcheology = true
travelersbackpack = true
things = true
railways = true
milk = true
ae2 = true
amendments = true
beautify = true
immersive_weathering = true
createcobblestone = true
snowrealmagic = true
lolmcv = true
createnuclear = true
biomesoplenty = true
expandeddelight = true
gravestones = true
